sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "Mc0ZrN8Q05vYCKyoZnK1sXIXWDzUMUkIK5Xru31yHNpuhgGdjfnVaB2ahLY0CEdlbO1zsNstj+C4JvjEZASsBsniKDRdBtRyYUPFoApI395JFuq3i49bg0sgquSzvJ/gZ2FjNCS/7YmDMInl0EFnvcnkd7PBRl9D1aEa+ICFOYScNt9B/bd/I2syJruTeDOSCXEzjN84kY4G+30JrNS5PrMNuRI7W1gNDAUWt/OxuCYNiv7UddPDAQwYvQ+RnXc4qQ3zOwy7UsQsYGYE5nNoHEnDaVrHO4BwDL04XJAjFWUSM/nBdY89jwPe6qo6L7EhcP40HjpgmDBTliCw0vcXGGOeyrNa+FRUw5SgagzaAXWjvmylziKFcv6Hxjz0WwdQOschGeqr2au673oo+DZoshR/1uAS5XcbuH76rTJDgcnYrlSktDKlLERLwOXAq/Fs2rlCzZYSA+3j/mlxk6NRtOQavlVukzAG0o9iFrrahTwJB+o+zhnexsmEtgLuyrn9wOeH6HNBGrrVi4K0LTRxWrQW13K18l0qGCFsSOfRm4zIIrqRNVICb/nVf9wiB8SFMKXMkvVBgjdgFkbrjR51eCzh2s84d4u7t4B+zUQMSRbPnIxzSkbO4FJaA/nZ5jM1LiU54+GnV21ARwwrq03WyXvgflWp9T2odVTG8pLux/A="
  - secure: "ftCwebsdcf4JLh+2U4UpdfmD/8HCAwAhgIWgmLnzAgfsVFmCGmy9nFig2uMvOHvVeYV8djoUuVLsGS+09JAey1J4fTYNARSx2Vp6cGzc+knG+FS+baRIIdkyJfjLlp/5voFQbBHPq/yA/y8WCoQy2r/Zx72b1sYRN1yGvP3lna019kYc8IPTiquDigkMpgQtfeWL9Dt23nrETJVROK5hSlCGV30vM7GWfosVvElnpMnlCQf3h9L4x/jECi+uuJvEjPxIvYnCEjxyUYhDPZgkdkge7ICM2PywlLra3rHCnpr2sgV4M6/OSFfnndsIzt5/CPtiHz9VEYo3bJXlLtSOZ1woUOn0etnnDNQ5E7UFweajTnksZLm865qP+jPzzWqmY4zVGjxkSFYvSWN+8siWlBgxpIxMhwZKS93q6hAwfBTByJ3UU2UjlrWZGXF8QIyp6GgFfOI+K9sfhPGNuj0lzVKC2U7tnZR95prnRcjb6REAUjPz1EGhNObnW5jmwD6YHVT8ewGICziLmRo7M7WmS4bzbJ5M+EbU24ZB5DHvn0JvYAUw3nnOe0ZivuDLf+wjV3QFNSf4ffrJd1mzFU7YQhyOdcwZnOiLnw5mzaR6UMjDUjrE2FzXn3jqmnVA/37TH9vgtDf/gPLo75kLMCl9k7wuZz2IYWmNkJXYtveJtEE="
  - secure: "fIdN0vJjS1RX/QLJHkE5LFChJPR5JaOeLEU34rbX6WBA2/1RPwpXYd3JrkfPdUGjWFXxg5cHTyoaKcFk/aYu/zfcoxvLav31RP8crISYtLMzlTkevsjPAdNyZxtmXe5F8Vf6RJmS8x3PYcritnvp4aLbQQgMZP5bn5TMq5z05bLINwoQJMHIeSfqbar2jfeeovOTAj1LknBOPM8Btbz6GBK0oD+2ALyS57sxRmTkazow5+FeyBe2YX7R6SFyaHz3r63s27D9rVduETknmpGS8TREcpMVViAjjM1bAZUlcZQjhbhzYAN4CuMgLlqjU6en5Pf1l/+nxsKMhcFp350nwyrOkLQ0Xp9n1RRZEP+Dm0glUF2U3bRuidtguo7Ag7Ozr8JXwfKY5TeDrLqjgOBmXyublZzTeK89566P8yFd1q2Z9xNKRxp0vcUepxAz7eZbLuqtxmqNyx5yNupyY5C/PkxsuyMkUkzt6UARsljtr3y9STQ1MayxR4MxGvISNCW876MeT6QlQ2REKr4d+L13hrJ/8bsk4/+UBdibUyBjNQZLvRceBN/8iPu6zfTMss6ksKvhO6+pp+gO8RrswlAJ+7wcBD29njv5yR3SDZevq35x+EzYPOocS66f03Yb6IO9hHx78v29sKR6t2vaFPtiYsZrQEPEOFWUElSbABd+MGI="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
