sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "f1fjXIfGk04f0QeAjQr2I5otd3JRQRsbizoctO0voIq05wRvlVkHdJBmk7fAHIY3EnuPoqz5YWIFH0tGgdSxoBfxCTt3FXpp2/X3GVcjoXIw9LN5CK0U1dxXYAMZLv7vH9vxt0O6AgaBI6gsQF3d51ECtR8pgL+ebuQvOG0PCJRiMgc8hHptaEMeTsGBQHY1A2Qz0IKIoNWKGSrFcUzL2z0eKJpM59hAvm3faK6Pre4KMZ4C7aBEQ5dDFqdy7dmLqGkbcS4kLPENoOqxB42CqdH3q9mRiuaj2JAMjmPXvQY/jFPhmZzJq3IPJ7W5Xu0tZ2F267UKh9P5cQc7kSf+jP7g+8wlJA9pOat8VQRDbh8ZMi3H9YwEExpxz8KANNTPSLQyvRRpB5cWGOIz3uE+bxgAq/T/nmo0/UPxFEPe92TCwufk3xznPRvcrQiW+FD8GEUSqaDFlqitIj6Z3Gr+F1K9qfbeuMJhQ1h7QpVxJWQZOEXar4wyOQoAU+RpnrftV0KQB6lvvOpCSUqvkr4+/P+Dnr7GnA4i9Pozqw1u0hGG3SLOPR4VvmVV3f8/JgX8Kc68+lFCKyXiZtId2XnDN/kOAPAwR+7iGOvKHUKzK9oTz0XDip5XoWZbhLfGbSxZJOp5lxSfPoLuXiBmpaHSQqniQ6EbpGdRofGtcA9r2V0="
  - secure: "ftCwebsdcf4JLh+2U4UpdfmD/8HCAwAhgIWgmLnzAgfsVFmCGmy9nFig2uMvOHvVeYV8djoUuVLsGS+09JAey1J4fTYNARSx2Vp6cGzc+knG+FS+baRIIdkyJfjLlp/5voFQbBHPq/yA/y8WCoQy2r/Zx72b1sYRN1yGvP3lna019kYc8IPTiquDigkMpgQtfeWL9Dt23nrETJVROK5hSlCGV30vM7GWfosVvElnpMnlCQf3h9L4x/jECi+uuJvEjPxIvYnCEjxyUYhDPZgkdkge7ICM2PywlLra3rHCnpr2sgV4M6/OSFfnndsIzt5/CPtiHz9VEYo3bJXlLtSOZ1woUOn0etnnDNQ5E7UFweajTnksZLm865qP+jPzzWqmY4zVGjxkSFYvSWN+8siWlBgxpIxMhwZKS93q6hAwfBTByJ3UU2UjlrWZGXF8QIyp6GgFfOI+K9sfhPGNuj0lzVKC2U7tnZR95prnRcjb6REAUjPz1EGhNObnW5jmwD6YHVT8ewGICziLmRo7M7WmS4bzbJ5M+EbU24ZB5DHvn0JvYAUw3nnOe0ZivuDLf+wjV3QFNSf4ffrJd1mzFU7YQhyOdcwZnOiLnw5mzaR6UMjDUjrE2FzXn3jqmnVA/37TH9vgtDf/gPLo75kLMCl9k7wuZz2IYWmNkJXYtveJtEE="
  - secure: "fIdN0vJjS1RX/QLJHkE5LFChJPR5JaOeLEU34rbX6WBA2/1RPwpXYd3JrkfPdUGjWFXxg5cHTyoaKcFk/aYu/zfcoxvLav31RP8crISYtLMzlTkevsjPAdNyZxtmXe5F8Vf6RJmS8x3PYcritnvp4aLbQQgMZP5bn5TMq5z05bLINwoQJMHIeSfqbar2jfeeovOTAj1LknBOPM8Btbz6GBK0oD+2ALyS57sxRmTkazow5+FeyBe2YX7R6SFyaHz3r63s27D9rVduETknmpGS8TREcpMVViAjjM1bAZUlcZQjhbhzYAN4CuMgLlqjU6en5Pf1l/+nxsKMhcFp350nwyrOkLQ0Xp9n1RRZEP+Dm0glUF2U3bRuidtguo7Ag7Ozr8JXwfKY5TeDrLqjgOBmXyublZzTeK89566P8yFd1q2Z9xNKRxp0vcUepxAz7eZbLuqtxmqNyx5yNupyY5C/PkxsuyMkUkzt6UARsljtr3y9STQ1MayxR4MxGvISNCW876MeT6QlQ2REKr4d+L13hrJ/8bsk4/+UBdibUyBjNQZLvRceBN/8iPu6zfTMss6ksKvhO6+pp+gO8RrswlAJ+7wcBD29njv5yR3SDZevq35x+EzYPOocS66f03Yb6IO9hHx78v29sKR6t2vaFPtiYsZrQEPEOFWUElSbABd+MGI="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
