sudo: false

language: c

addons:
  apt:
    packages:
    - luarocks

env:
  global:
  - secure: "Tec3lZPqy0wurCzjMoLawJ6QKIR4ngtE9cX/fHIJL9Iwj1jmgfS8E29gpNKTzc+zXNyk6Z5Fx/TPJ+PO9D1cMS39um5WLTk9/TPMzLrISCEpOxRWDfIAxq8EzJMpSc8pijba7xsR/CHFsrrVZHwmtD8fGXlr4IPQ9i5ghNTCq0sloOt3noOwSLKuGASeMJENDgg1P0TUKX7ocb7y/UhGQ9ggTK6UH8YLDb+mO4iWyUkuhA+KAYa02jgiqzs9weJwQrbpIGGd8/tcjXGI3XpSJXr2+4u+M3srzOpZYF1yf2CkozhoaMsjDB74IDRR2u/xtIOvCgydZ0ok2rFNh+1ehSK0EfhO94oCrIflGoATUHGOPqR+Fhpf4EitaOgwhEy7qmcKs/LJQbXy76AGTFpC/5E2aeN8JDbOaQZutvUTAWLERuKGBGT3bN2HH/3Zj5jI6LqIt5m+TC93He9bxOM4yo/GFfhDvDACSgB5J00kWZ6FcmyhqDgiHBRp5CDBG8jM/IxF14F/O8RdvGPmgVD7PUd8TSrBey8OFUJx/JpN+85kvGxBB8Dj5cr6AOpKqVSGmVpDU2QhN86bPQ/l6Ax5ayVMgwgCFXHHXhyf+AJZIzwK7yBzOWRzihGdSGr8ju85A4fFIOmg2LfMHtCY0He7yHjdHuNdfqYNz7m6Jajmmho="
  - secure: "fTFi9Pow/wLceEUfj0j1hsPsWpDLBkngJOKVmTurPTrb/kJuy7qBzduqLQ/aAZC84/17eV391VAT0ia3PeKaIaVQ011CEsEzjIFxIopt9lpx7g6R2v5/vMPqxghtjQ7lSc5YjhSs/HC80Ly96zbheXLeUCAXzWUdrcr50L8AUNzc3OiKebAuvb8w/5IzSw6lB6c7kmsYBYKNoBY3fdUBmlyBPwRdfKFwiIbfrIXLKoB5V/dbILewZgAFIr84fZcWFfmWoofCOrtckz03WCmjWZdoq5HbCiabrCFR7Cl88+Gkk+lBfIlRIFdP63NGjfkWGgzOcB7fFdaIaHi60nR7RtFIGxFPiub5RHyZAhhCufHl1l26uCDGcfnMG0mvEgkrvke1Smf7R8+4OhWceotMx2kZSdUuFQBIgMzyKKQ85e7rbz7z34ysTSXS6R+2vYb1Q3qfwNtKiSMLjHUbVeo1Fi2TCYgoaLkP7VEGdbiybH4hO/x2GZqMeZH8HO0m0rdmH0APxY+nWPKXspPp1XsHlJ3nWDbH41MAryytYyC2Aa3SrcVgLlQzCBRP9x3uzMRFnTdON+UGbDAhuU1Il2PH/O+XYn7TNUhVqKDFE7Dn6ckvUDW79rYtaebMEjFkuMNfA2j3VXRf9O61s+726coaozXp4u/sXSHKJYfErD3RYQE="
  - secure: "RT2DzAZXoGcs7BPKJSj9p1ksscJRMdi9vSBA97RZayzY8OVPTTvjEbcX9x4qQ0VACcRHHzeTxPSk7B6O+HzRlzDzjKGhLG/1dC913MG2h64DOQoz8H0aQaf31tEkB6/zineMvNhuxlDOnulEILTdd8XasnRMn6YjDR7ACJXOSbcN5Ea1mj94ow9BbSx2apWbWGP7wl0kV4Ae/LhtpIHzWDNRxjXGw4LMBnssMsjF1+cUCO5jtlrtToSHtJXY0ytDqCe0UYbfLx0OilN9V1Xv0OTYWWQPof6cNOhJPuimbWQS4lta+g+Xh30+Eefhkx5xriuLYmfIIw5zENDjSVt1OHiqbzQq/P7WNc8I1kcglBmizE4tCit+Wa0QF6wATwPanzGpAaCMRAJlD78RLsl8LoHnDqLI0b9/w21ETauTVUPFDPuxItuqmLkMDPB/xP7n8Zm+ROfY1nrpw8txvpK8LBKdz7SXBg3bRNuuxio0aaAP4kvkKdK9QtkhbOsSuU/ZkQ255+Pitf7XVlftSSQnjpRC5nD18TWV0E+sxyUVvbsfFDfUcn7ZbYF4qKcUKbaCmXWCAQ/1bTrAeGy1N7a0PtcwJGYDSCeXzP/XNvv7EIeLc7X5m0NIcaG0gvxrccTP1vPPx1hIfG7Sfl8pfpg/1/MF9rOvn/yoJvFBDjPf/S0="

before_install: luarocks install --local luacheck

before_script: /home/travis/.luarocks/bin/luacheck . --no-color -qo "011"
script: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

notifications:
  email:
    on_success: never
    on_failure: always
